# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_kUMBaDsIz47SR2CbhO3pmKzU_Hy91Z

## Load the data

### Subtask:
Load the `Housing.csv` file into a pandas DataFrame.

**Reasoning**:
Load the data into a pandas DataFrame and display the first few rows.
"""

import pandas as pd

df = pd.read_csv('/content/Housing.csv')
display(df.head())

"""## Analyze price ranges

### Subtask:
Define the price ranges (0-25 lakhs, 26-50 lakhs, etc.), count the number of houses in each range, and visualize the counts using a line chart.

**Reasoning**:
Define price ranges, categorize houses into these ranges, count houses in each range, and visualize the counts using a line chart.
"""

price_ranges = [(0, 2500000), (2500001, 5000000), (5000001, 7500000), (7500001, 10000000), (10000001, df['price'].max())]
range_labels = ['0-25L', '26-50L', '51-75L', '76-100L', '>100L']

df['price_range'] = pd.cut(df['price'], bins=[r[0] for r in price_ranges] + [price_ranges[-1][1]], labels=range_labels, right=True)

price_range_counts = df['price_range'].value_counts().sort_index()

plt.figure(figsize=(10, 6))
plt.plot(price_range_counts.index, price_range_counts.values, marker='o')
plt.xlabel('Price Range')
plt.ylabel('Number of Houses')
plt.title('Number of Houses in Different Price Ranges')
plt.grid(True)
plt.show()

"""**Reasoning**:
The previous code block failed because the `matplotlib.pyplot` library was not imported. I will add the import statement and regenerate the full code block to define the price ranges, categorize houses, count houses in each range, and visualize the counts using a line chart.


"""

import matplotlib.pyplot as plt

price_ranges = [(0, 2500000), (2500001, 5000000), (5000001, 7500000), (7500001, 10000000), (10000001, df['price'].max())]
range_labels = ['0-25L', '26-50L', '51-75L', '76-100L', '>100L']

df['price_range'] = pd.cut(df['price'], bins=[r[0] for r in price_ranges] + [price_ranges[-1][1]], labels=range_labels, right=True)

price_range_counts = df['price_range'].value_counts().sort_index()

plt.figure(figsize=(10, 6))
plt.plot(price_range_counts.index, price_range_counts.values, marker='o')
plt.xlabel('Price Range')
plt.ylabel('Number of Houses')
plt.title('Number of Houses in Different Price Ranges')
plt.grid(True)
plt.show()

"""## Analyze average prices for ac vs. non-ac houses

### Subtask:
Calculate the average price for houses with AC and without AC and visualize the relationship using a bar chart.

**Reasoning**:
Group the DataFrame by 'airconditioning' and calculate the mean price, then create a bar chart to visualize the results.
"""

average_price_by_ac = df.groupby('airconditioning')['price'].mean()

plt.figure(figsize=(8, 5))
plt.bar(average_price_by_ac.index, average_price_by_ac.values, color=['skyblue', 'lightcoral'])
plt.xlabel('Air Conditioning')
plt.ylabel('Average Price')
plt.title('Average House Price with and without AC')
plt.show()

"""## Simulate the relationship between parking and house price

### Subtask:
Explore the relationship between the number of parking spaces and house prices.

**Reasoning**:
Group the DataFrame by the 'parking' column and calculate the mean of the 'price'. Then create and display a bar chart to visualize this relationship, including labels and a title.
"""

average_price_by_parking = df.groupby('parking')['price'].mean()

plt.figure(figsize=(8, 5))
plt.bar(average_price_by_parking.index, average_price_by_parking.values, color='teal')
plt.xlabel('Number of Parking Spaces')
plt.ylabel('Average Price')
plt.title('Average House Price by Number of Parking Spaces')
plt.show()

"""## Calculate price gap for area and preferred area

### Subtask:
Filter houses based on area (<5000 sqft and no prefarea) and (>5000 sqft and prefarea). Calculate the average price for each group. Determine the price gap between the two groups.

**Reasoning**:
Create two dataframes based on area and prefarea conditions, calculate the average price for each, find the difference, and print the results.
"""

filtered_df_group1 = df[(df['area'] < 5000) & (df['prefarea'] == 'no')]
filtered_df_group2 = df[(df['area'] > 5000) & (df['prefarea'] == 'yes')]

average_price_group1 = filtered_df_group1['price'].mean()
average_price_group2 = filtered_df_group2['price'].mean()

price_gap = average_price_group2 - average_price_group1

print(f"Average price for houses with <5000 sqft and no prefarea: {average_price_group1:,.2f}")
print(f"Average price for houses with >5000 sqft and prefarea: {average_price_group2:,.2f}")
print(f"Price gap between the two groups: {price_gap:,.2f}")

"""## Present the findings

### Subtask:
Summarize the results and visualizations from the previous analysis steps.

## Summary:

### Data Analysis Key Findings

*   The majority of houses are priced between \$26L and \$75L.
*   Houses with air conditioning have a significantly higher average price than those without.
*   The average house price tends to increase with the number of parking spaces.
*   There is a substantial price gap between houses with an area less than 5000 sqft and no preferred area (average price around \$3,827,671.56) and houses with an area greater than 5000 sqft and a preferred area (average price around \$6,546,807.69). The price gap is approximately \$2,719,136.13.

### Insights or Next Steps

*   Investigate other factors that might influence house prices, such as the number of bedrooms, bathrooms, and the presence of other amenities like a basement or main road access.
*   Perform a regression analysis to quantify the impact of each feature (including area, AC, parking, and preferred area) on the house price.
"""